"""empty message

Revision ID: ea30dc62aadc
Revises: 
Create Date: 2018-01-20 16:09:15.834020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea30dc62aadc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=140), nullable=True),
    sa.Column('password', sa.String(length=140), nullable=True),
    sa.Column('email', sa.String(length=140), nullable=True),
    sa.Column('phone', sa.String(length=140), nullable=True),
    sa.Column('full_name', sa.String(length=140), nullable=True),
    sa.Column('access_level', sa.Integer(), nullable=True),
    sa.Column('email_verified', sa.BOOLEAN(), nullable=True),
    sa.Column('email_verification_code', sa.Text(), nullable=True),
    sa.Column('password_reset_code', sa.Text(), nullable=True),
    sa.Column('google_id_token', sa.Text(), nullable=True),
    sa.Column('mobile_access_token', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('user_id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
